return LPH_NO_VIRTUALIZE(function()
        local tbl =
        {
            Spectate = Instance.new("Frame"),
            StatBars = Instance.new("Frame"),
            Health = Instance.new("Frame"),
            Padding = Instance.new("Frame"),
            StatLabel = Instance.new("ImageLabel"),
            Bar = Instance.new("ImageLabel"),
            UIGradient = Instance.new("UIGradient"),
            Arrows = Instance.new("Frame"),
            Up = Instance.new("Frame"),
            _1 = Instance.new("ImageLabel"),
            _2 = Instance.new("ImageLabel"),
            _3 = Instance.new("ImageLabel"),
            Down = Instance.new("Frame"),
            _1_1 = Instance.new("ImageLabel"),
            _2_1 = Instance.new("ImageLabel"),
            _3_1 = Instance.new("ImageLabel"),
            Booster = Instance.new("ImageLabel"),
            Shadow = Instance.new("ImageLabel"),
            UIGradient_1 = Instance.new("UIGradient"),
            Energy = Instance.new("Frame"),
            Padding_1 = Instance.new("Frame"),
            StatLabel_1 = Instance.new("ImageLabel"),
            Bar_1 = Instance.new("ImageLabel"),
            UIGradient_2 = Instance.new("UIGradient"),
            Arrows_1 = Instance.new("Frame"),
            Up_1 = Instance.new("Frame"),
            _1_2 = Instance.new("ImageLabel"),
            _2_2 = Instance.new("ImageLabel"),
            _3_2 = Instance.new("ImageLabel"),
            Down_1 = Instance.new("Frame"),
            _1_3 = Instance.new("ImageLabel"),
            _2_3 = Instance.new("ImageLabel"),
            _3_3 = Instance.new("ImageLabel"),
            Booster_1 = Instance.new("ImageLabel"),
            Shadow_1 = Instance.new("ImageLabel"),
            UIGradient_3 = Instance.new("UIGradient"),
            Hydration = Instance.new("Frame"),
            Padding_2 = Instance.new("Frame"),
            StatLabel_2 = Instance.new("ImageLabel"),
            Bar_2 = Instance.new("ImageLabel"),
            UIGradient_4 = Instance.new("UIGradient"),
            Arrows_2 = Instance.new("Frame"),
            Up_2 = Instance.new("Frame"),
            _1_4 = Instance.new("ImageLabel"),
            _2_4 = Instance.new("ImageLabel"),
            _3_4 = Instance.new("ImageLabel"),
            Down_2 = Instance.new("Frame"),
            _1_5 = Instance.new("ImageLabel"),
            _2_5 = Instance.new("ImageLabel"),
            _3_5 = Instance.new("ImageLabel"),
            Booster_2 = Instance.new("ImageLabel"),
            Shadow_2 = Instance.new("ImageLabel"),
            UIGradient_5 = Instance.new("UIGradient"),
            UIScale = Instance.new("UIScale"),
            Decoration = Instance.new("Frame"),
            ShadowFrame = Instance.new("Frame"),
            Shadow_3 = Instance.new("ImageLabel"),
            Wrap = Instance.new("ImageLabel"),
            TextBox = Instance.new("TextBox"),
            UICorner = Instance.new("UICorner"),
            TextBox_1 = Instance.new("TextBox"),
            UICorner_1 = Instance.new("UICorner"),
            Players = Instance.new("Frame"),
            Label = Instance.new("TextLabel"),
            UICorner_2 = Instance.new("UICorner"),
            Back = Instance.new("TextButton"),
            UICorner_3 = Instance.new("UICorner"),
            Next = Instance.new("TextButton"),
            UICorner_4 = Instance.new("UICorner"),
            StatLabels = Instance.new("Frame"),
            UIGridLayout = Instance.new("UIGridLayout"),
            UIPadding = Instance.new("UIPadding"),
            Menu = Instance.new("Frame"),
            Title = Instance.new("TextLabel"),
            Info = Instance.new("TextLabel"),
            Equipped = Instance.new("Frame"),
            Title_1 = Instance.new("TextLabel"),
            Info_1 = Instance.new("TextLabel"),
            Ping = Instance.new("Frame"),
            Title_2 = Instance.new("TextLabel"),
            Info_2 = Instance.new("TextLabel"),
            MoveState = Instance.new("Frame"),
            Title_3 = Instance.new("TextLabel"),
            Info_3 = Instance.new("TextLabel"),
            FirstPerson = Instance.new("Frame"),
            Title_4 = Instance.new("TextLabel"),
            Info_4 = Instance.new("TextLabel"),
            MoveSpeed = Instance.new("Frame"),
            Title_5 = Instance.new("TextLabel"),
            Info_5 = Instance.new("TextLabel"),
            Zooming = Instance.new("Frame"),
            Title_6 = Instance.new("TextLabel"),
            Info_6 = Instance.new("TextLabel"),
            CombatTime = Instance.new("Frame"),
            Title_7 = Instance.new("TextLabel"),
            Info_7 = Instance.new("TextLabel"),
            Groups = Instance.new("Frame"),
            Label_1 = Instance.new("TextLabel"),
            UICorner_5 = Instance.new("UICorner"),
            Back_1 = Instance.new("TextButton"),
            UICorner_6 = Instance.new("UICorner"),
            Next_1 = Instance.new("TextButton"),
            UICorner_7 = Instance.new("UICorner"),
            Backdrop = Instance.new("Frame"),
            UICorner_8 = Instance.new("UICorner")
        }

    tbl.Spectate.AnchorPoint = Vector2.new(0.5, 1); tbl.Spectate.ZIndex = 10; tbl.Spectate.BorderSizePixel = 0; tbl.Spectate.Size = UDim2.new(0, 489, 0, 62); tbl.Spectate.AutoLocalize = false; tbl.Spectate.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Spectate.BackgroundTransparency = 1; tbl.Spectate.Name = "Spectate"; tbl.Spectate.Position = UDim2.new(0.5, 0, 1, -20); tbl.Spectate.BackgroundColor3 = Color3.fromRGB(0, 0, 0); tbl.Spectate.Visible = false;
    tbl.StatBars.ZIndex = 61; tbl.StatBars.BorderSizePixel = 0; tbl.StatBars.Size = UDim2.new(0, 489, 0, 16); tbl.StatBars.AutoLocalize = false; tbl.StatBars.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.StatBars.BackgroundTransparency = 1; tbl.StatBars.Name = "StatBars"; tbl.StatBars.Position = UDim2.new(0, 0, 0, 64); tbl.StatBars.BackgroundColor3 = Color3.fromRGB(0, 0, 0); tbl.StatBars.Parent = tbl.Spectate; 
    tbl.Health.ZIndex = 62; tbl.Health.BorderSizePixel = 0; tbl.Health.Size = UDim2.new(0, 162, 0, 16); tbl.Health.AutoLocalize = false; tbl.Health.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Health.Name = "Health"; tbl.Health.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Health.Parent = tbl.StatBars; 
    tbl.Padding.ZIndex = 63; tbl.Padding.BorderSizePixel = 0; tbl.Padding.Size = UDim2.new(1, -2, 1, -2); tbl.Padding.AutoLocalize = false; tbl.Padding.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Padding.Name = "Padding"; tbl.Padding.Position = UDim2.new(0, 1, 0, 1); tbl.Padding.BackgroundColor3 = Color3.fromRGB(0, 0, 0); tbl.Padding.Parent = tbl.Health; 
    tbl.StatLabel.ZIndex = 65; tbl.StatLabel.BorderSizePixel = 0; tbl.StatLabel.SliceCenter = Rect.new(5, 5, 5, 5); tbl.StatLabel.AutoLocalize = false; tbl.StatLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.StatLabel.AnchorPoint = Vector2.new(0.5, 0); tbl.StatLabel.Image = "http://www.roblox.com/asset/?id=4841924670"; tbl.StatLabel.Size = UDim2.new(1, 0, 0, 14); tbl.StatLabel.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.StatLabel.Name = "StatLabel"; tbl.StatLabel.BackgroundTransparency = 1; tbl.StatLabel.Position = UDim2.new(0.5, 0, 0, 0); tbl.StatLabel.SliceScale = 0; tbl.StatLabel.Parent = tbl.Padding; 
    tbl.Bar.ZIndex = 63; tbl.Bar.BorderSizePixel = 0; tbl.Bar.SliceCenter = Rect.new(5, 5, 5, 5); tbl.Bar.AutoLocalize = false; tbl.Bar.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Bar.Size = UDim2.new(1, 0, 1, 0); tbl.Bar.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Bar.Name = "Bar"; tbl.Bar.SliceScale = 0; tbl.Bar.Parent = tbl.Padding; 
    tbl.UIGradient.Name = "UIGradient"; tbl.UIGradient.Color = ColorSequence.new{ ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 128, 123)), ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 222, 151)) }; tbl.UIGradient.Rotation = 90; tbl.UIGradient.Parent = tbl.Bar; 
    tbl.Arrows.AnchorPoint = Vector2.new(1, 0); tbl.Arrows.ZIndex = 62; tbl.Arrows.BorderSizePixel = 0; tbl.Arrows.Size = UDim2.new(0, 30, 1, 0); tbl.Arrows.AutoLocalize = false; tbl.Arrows.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Arrows.BackgroundTransparency = 1; tbl.Arrows.Name = "Arrows"; tbl.Arrows.Position = UDim2.new(1, 0, 0, 0); tbl.Arrows.BackgroundColor3 = Color3.fromRGB(0, 0, 0); tbl.Arrows.Parent = tbl.Padding; 
    tbl.Up.ZIndex = 61; tbl.Up.Size = UDim2.new(1, 0, 1, 0); tbl.Up.AutoLocalize = false; tbl.Up.BackgroundTransparency = 1; tbl.Up.Visible = false; tbl.Up.Name = "Up"; tbl.Up.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Up.Parent = tbl.Arrows; 
    tbl._1.ZIndex = 70; tbl._1.BorderSizePixel = 0; tbl._1.AutoLocalize = false; tbl._1.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._1.AnchorPoint = Vector2.new(1, 0); tbl._1.Image = "http://www.roblox.com/asset/?id=4841959138"; tbl._1.Size = UDim2.new(0, 11, 0, 14); tbl._1.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._1.Name = "1"; tbl._1.BackgroundTransparency = 1; tbl._1.Position = UDim2.new(1, 0, 0, 0); tbl._1.Visible = false; tbl._1.Parent = tbl.Up; 
    tbl._2.ZIndex = 70; tbl._2.BorderSizePixel = 0; tbl._2.AutoLocalize = false; tbl._2.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._2.AnchorPoint = Vector2.new(1, 0); tbl._2.Image = "http://www.roblox.com/asset/?id=4841959138"; tbl._2.Size = UDim2.new(0, 11, 0, 14); tbl._2.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._2.Name = "2"; tbl._2.BackgroundTransparency = 1; tbl._2.Position = UDim2.new(1, -9, 0, 0); tbl._2.Visible = false; tbl._2.Parent = tbl.Up; 
    tbl._3.ZIndex = 70; tbl._3.BorderSizePixel = 0; tbl._3.AutoLocalize = false; tbl._3.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._3.AnchorPoint = Vector2.new(1, 0); tbl._3.Image = "http://www.roblox.com/asset/?id=4841959138"; tbl._3.Size = UDim2.new(0, 11, 0, 14); tbl._3.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._3.Name = "3"; tbl._3.BackgroundTransparency = 1; tbl._3.Position = UDim2.new(1, -18, 0, 0); tbl._3.Visible = false; tbl._3.Parent = tbl.Up; 
    tbl.Down.ZIndex = 61; tbl.Down.Size = UDim2.new(1, 0, 1, 0); tbl.Down.AutoLocalize = false; tbl.Down.BackgroundTransparency = 1; tbl.Down.Visible = false; tbl.Down.Name = "Down"; tbl.Down.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Down.Parent = tbl.Arrows; 
    tbl._1_1.ZIndex = 70; tbl._1_1.BorderSizePixel = 0; tbl._1_1.AutoLocalize = false; tbl._1_1.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._1_1.AnchorPoint = Vector2.new(1, 0); tbl._1_1.Image = "http://www.roblox.com/asset/?id=4841959303"; tbl._1_1.Size = UDim2.new(0, 11, 0, 14); tbl._1_1.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._1_1.Name = "1"; tbl._1_1.BackgroundTransparency = 1; tbl._1_1.Position = UDim2.new(1, 0, 0, 0); tbl._1_1.Visible = false; tbl._1_1.Parent = tbl.Down; 
    tbl._2_1.ZIndex = 70; tbl._2_1.BorderSizePixel = 0; tbl._2_1.AutoLocalize = false; tbl._2_1.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._2_1.AnchorPoint = Vector2.new(1, 0); tbl._2_1.Image = "http://www.roblox.com/asset/?id=4841959303"; tbl._2_1.Size = UDim2.new(0, 11, 0, 14); tbl._2_1.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._2_1.Name = "2"; tbl._2_1.BackgroundTransparency = 1; tbl._2_1.Position = UDim2.new(1, -9, 0, 0); tbl._2_1.Visible = false; tbl._2_1.Parent = tbl.Down; 
    tbl._3_1.ZIndex = 70; tbl._3_1.BorderSizePixel = 0; tbl._3_1.AutoLocalize = false; tbl._3_1.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._3_1.AnchorPoint = Vector2.new(1, 0); tbl._3_1.Image = "http://www.roblox.com/asset/?id=4841959303"; tbl._3_1.Size = UDim2.new(0, 11, 0, 14); tbl._3_1.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._3_1.Name = "3"; tbl._3_1.BackgroundTransparency = 1; tbl._3_1.Position = UDim2.new(1, -18, 0, 0); tbl._3_1.Visible = false; tbl._3_1.Parent = tbl.Down; 
    tbl.Booster.ZIndex = 64; tbl.Booster.BorderSizePixel = 0; tbl.Booster.SliceCenter = Rect.new(5, 5, 5, 5); tbl.Booster.AutoLocalize = false; tbl.Booster.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Booster.Size = UDim2.new(0, 0, 1, 0); tbl.Booster.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Booster.Name = "Booster"; tbl.Booster.SliceScale = 0; tbl.Booster.Parent = tbl.Padding; 
    tbl.Shadow.ZIndex = 64; tbl.Shadow.BorderSizePixel = 0; tbl.Shadow.SliceCenter = Rect.new(5, 5, 5, 5); tbl.Shadow.AutoLocalize = false; tbl.Shadow.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Shadow.ImageTransparency = 1; tbl.Shadow.Image = "http://www.roblox.com/asset/?id=4841891466"; tbl.Shadow.Size = UDim2.new(0, 14, 1, 0); tbl.Shadow.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Shadow.Name = "Shadow"; tbl.Shadow.BackgroundTransparency = 1; tbl.Shadow.Position = UDim2.new(1, 0, 0, 0); tbl.Shadow.SliceScale = 0; tbl.Shadow.Parent = tbl.Booster; 
    tbl.UIGradient_1.Name = "UIGradient"; tbl.UIGradient_1.Color = ColorSequence.new{ ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 123, 107)), ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 237, 86)) }; tbl.UIGradient_1.Rotation = 90; tbl.UIGradient_1.Parent = tbl.Booster; 
    tbl.Energy.ZIndex = 62; tbl.Energy.BorderSizePixel = 0; tbl.Energy.Size = UDim2.new(0, 161, 0, 16); tbl.Energy.AutoLocalize = false; tbl.Energy.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Energy.Name = "Energy"; tbl.Energy.Position = UDim2.new(0, 164, 0, 0); tbl.Energy.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Energy.Parent = tbl.StatBars; 
    tbl.Padding_1.ZIndex = 63; tbl.Padding_1.BorderSizePixel = 0; tbl.Padding_1.Size = UDim2.new(1, -2, 1, -2); tbl.Padding_1.AutoLocalize = false; tbl.Padding_1.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Padding_1.Name = "Padding"; tbl.Padding_1.Position = UDim2.new(0, 1, 0, 1); tbl.Padding_1.BackgroundColor3 = Color3.fromRGB(0, 0, 0); tbl.Padding_1.Parent = tbl.Energy; 
    tbl.StatLabel_1.ZIndex = 65; tbl.StatLabel_1.BorderSizePixel = 0; tbl.StatLabel_1.SliceCenter = Rect.new(5, 5, 5, 5); tbl.StatLabel_1.AutoLocalize = false; tbl.StatLabel_1.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.StatLabel_1.AnchorPoint = Vector2.new(0.5, 0); tbl.StatLabel_1.Image = "http://www.roblox.com/asset/?id=4841924877"; tbl.StatLabel_1.Size = UDim2.new(1, 0, 0, 14); tbl.StatLabel_1.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.StatLabel_1.Name = "StatLabel"; tbl.StatLabel_1.BackgroundTransparency = 1; tbl.StatLabel_1.Position = UDim2.new(0.5, 0, 0, 0); tbl.StatLabel_1.SliceScale = 0; tbl.StatLabel_1.Parent = tbl.Padding_1; 
    tbl.Bar_1.ZIndex = 63; tbl.Bar_1.BorderSizePixel = 0; tbl.Bar_1.SliceCenter = Rect.new(5, 5, 5, 5); tbl.Bar_1.AutoLocalize = false; tbl.Bar_1.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Bar_1.Size = UDim2.new(1, 0, 1, 0); tbl.Bar_1.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Bar_1.Name = "Bar"; tbl.Bar_1.SliceScale = 0; tbl.Bar_1.Parent = tbl.Padding_1; 
    tbl.UIGradient_2.Name = "UIGradient"; tbl.UIGradient_2.Color = ColorSequence.new{ ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 128, 123)), ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 222, 151)) }; tbl.UIGradient_2.Rotation = 90; tbl.UIGradient_2.Parent = tbl.Bar_1; 
    tbl.Arrows_1.AnchorPoint = Vector2.new(1, 0); tbl.Arrows_1.ZIndex = 62; tbl.Arrows_1.BorderSizePixel = 0; tbl.Arrows_1.Size = UDim2.new(0, 30, 1, 0); tbl.Arrows_1.AutoLocalize = false; tbl.Arrows_1.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Arrows_1.BackgroundTransparency = 1; tbl.Arrows_1.Name = "Arrows"; tbl.Arrows_1.Position = UDim2.new(1, 0, 0, 0); tbl.Arrows_1.BackgroundColor3 = Color3.fromRGB(0, 0, 0); tbl.Arrows_1.Parent = tbl.Padding_1; 
    tbl.Up_1.ZIndex = 61; tbl.Up_1.Size = UDim2.new(1, 0, 1, 0); tbl.Up_1.AutoLocalize = false; tbl.Up_1.BackgroundTransparency = 1; tbl.Up_1.Visible = false; tbl.Up_1.Name = "Up"; tbl.Up_1.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Up_1.Parent = tbl.Arrows_1; 
    tbl._1_2.ZIndex = 70; tbl._1_2.BorderSizePixel = 0; tbl._1_2.AutoLocalize = false; tbl._1_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._1_2.AnchorPoint = Vector2.new(1, 0); tbl._1_2.Image = "http://www.roblox.com/asset/?id=4841959138"; tbl._1_2.Size = UDim2.new(0, 11, 0, 14); tbl._1_2.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._1_2.Name = "1"; tbl._1_2.BackgroundTransparency = 1; tbl._1_2.Position = UDim2.new(1, 0, 0, 0); tbl._1_2.Visible = false; tbl._1_2.Parent = tbl.Up_1; 
    tbl._2_2.ZIndex = 70; tbl._2_2.BorderSizePixel = 0; tbl._2_2.AutoLocalize = false; tbl._2_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._2_2.AnchorPoint = Vector2.new(1, 0); tbl._2_2.Image = "http://www.roblox.com/asset/?id=4841959138"; tbl._2_2.Size = UDim2.new(0, 11, 0, 14); tbl._2_2.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._2_2.Name = "2"; tbl._2_2.BackgroundTransparency = 1; tbl._2_2.Position = UDim2.new(1, -9, 0, 0); tbl._2_2.Visible = false; tbl._2_2.Parent = tbl.Up_1; 
    tbl._3_2.ZIndex = 70; tbl._3_2.BorderSizePixel = 0; tbl._3_2.AutoLocalize = false; tbl._3_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._3_2.AnchorPoint = Vector2.new(1, 0); tbl._3_2.Image = "http://www.roblox.com/asset/?id=4841959138"; tbl._3_2.Size = UDim2.new(0, 11, 0, 14); tbl._3_2.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._3_2.Name = "3"; tbl._3_2.BackgroundTransparency = 1; tbl._3_2.Position = UDim2.new(1, -18, 0, 0); tbl._3_2.Visible = false; tbl._3_2.Parent = tbl.Up_1; 
    tbl.Down_1.ZIndex = 61; tbl.Down_1.Size = UDim2.new(1, 0, 1, 0); tbl.Down_1.AutoLocalize = false; tbl.Down_1.BackgroundTransparency = 1; tbl.Down_1.Visible = false; tbl.Down_1.Name = "Down"; tbl.Down_1.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Down_1.Parent = tbl.Arrows_1; 
    tbl._1_3.ZIndex = 70; tbl._1_3.BorderSizePixel = 0; tbl._1_3.AutoLocalize = false; tbl._1_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._1_3.AnchorPoint = Vector2.new(1, 0); tbl._1_3.Image = "http://www.roblox.com/asset/?id=4841959303"; tbl._1_3.Size = UDim2.new(0, 11, 0, 14); tbl._1_3.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._1_3.Name = "1"; tbl._1_3.BackgroundTransparency = 1; tbl._1_3.Position = UDim2.new(1, 0, 0, 0); tbl._1_3.Visible = false; tbl._1_3.Parent = tbl.Down_1; 
    tbl._2_3.ZIndex = 70; tbl._2_3.BorderSizePixel = 0; tbl._2_3.AutoLocalize = false; tbl._2_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._2_3.AnchorPoint = Vector2.new(1, 0); tbl._2_3.Image = "http://www.roblox.com/asset/?id=4841959303"; tbl._2_3.Size = UDim2.new(0, 11, 0, 14); tbl._2_3.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._2_3.Name = "2"; tbl._2_3.BackgroundTransparency = 1; tbl._2_3.Position = UDim2.new(1, -9, 0, 0); tbl._2_3.Visible = false; tbl._2_3.Parent = tbl.Down_1; 
    tbl._3_3.ZIndex = 70; tbl._3_3.BorderSizePixel = 0; tbl._3_3.AutoLocalize = false; tbl._3_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._3_3.AnchorPoint = Vector2.new(1, 0); tbl._3_3.Image = "http://www.roblox.com/asset/?id=4841959303"; tbl._3_3.Size = UDim2.new(0, 11, 0, 14); tbl._3_3.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._3_3.Name = "3"; tbl._3_3.BackgroundTransparency = 1; tbl._3_3.Position = UDim2.new(1, -18, 0, 0); tbl._3_3.Visible = false; tbl._3_3.Parent = tbl.Down_1; 
    tbl.Booster_1.ZIndex = 64; tbl.Booster_1.BorderSizePixel = 0; tbl.Booster_1.SliceCenter = Rect.new(5, 5, 5, 5); tbl.Booster_1.AutoLocalize = false; tbl.Booster_1.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Booster_1.Size = UDim2.new(0, 0, 1, 0); tbl.Booster_1.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Booster_1.Name = "Booster"; tbl.Booster_1.SliceScale = 0; tbl.Booster_1.Parent = tbl.Padding_1; 
    tbl.Shadow_1.ZIndex = 64; tbl.Shadow_1.BorderSizePixel = 0; tbl.Shadow_1.SliceCenter = Rect.new(5, 5, 5, 5); tbl.Shadow_1.AutoLocalize = false; tbl.Shadow_1.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Shadow_1.ImageTransparency = 1; tbl.Shadow_1.Image = "http://www.roblox.com/asset/?id=4841891466"; tbl.Shadow_1.Size = UDim2.new(0, 14, 1, 0); tbl.Shadow_1.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Shadow_1.Name = "Shadow"; tbl.Shadow_1.BackgroundTransparency = 1; tbl.Shadow_1.Position = UDim2.new(1, 0, 0, 0); tbl.Shadow_1.SliceScale = 0; tbl.Shadow_1.Parent = tbl.Booster_1; 
    tbl.UIGradient_3.Name = "UIGradient"; tbl.UIGradient_3.Color = ColorSequence.new{ ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 123, 107)), ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 237, 86)) }; tbl.UIGradient_3.Rotation = 90; tbl.UIGradient_3.Parent = tbl.Booster_1; 
    tbl.Hydration.ZIndex = 62; tbl.Hydration.BorderSizePixel = 0; tbl.Hydration.Size = UDim2.new(0, 162, 0, 16); tbl.Hydration.AutoLocalize = false; tbl.Hydration.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Hydration.Name = "Hydration"; tbl.Hydration.Position = UDim2.new(0, 327, 0, 0); tbl.Hydration.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Hydration.Parent = tbl.StatBars; 
    tbl.Padding_2.ZIndex = 63; tbl.Padding_2.BorderSizePixel = 0; tbl.Padding_2.Size = UDim2.new(1, -2, 1, -2); tbl.Padding_2.AutoLocalize = false; tbl.Padding_2.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Padding_2.Name = "Padding"; tbl.Padding_2.Position = UDim2.new(0, 1, 0, 1); tbl.Padding_2.BackgroundColor3 = Color3.fromRGB(0, 0, 0); tbl.Padding_2.Parent = tbl.Hydration; 
    tbl.StatLabel_2.ZIndex = 65; tbl.StatLabel_2.BorderSizePixel = 0; tbl.StatLabel_2.SliceCenter = Rect.new(5, 5, 5, 5); tbl.StatLabel_2.AutoLocalize = false; tbl.StatLabel_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.StatLabel_2.AnchorPoint = Vector2.new(0.5, 0); tbl.StatLabel_2.Image = "http://www.roblox.com/asset/?id=4841925072"; tbl.StatLabel_2.Size = UDim2.new(1, 0, 0, 14); tbl.StatLabel_2.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.StatLabel_2.Name = "StatLabel"; tbl.StatLabel_2.BackgroundTransparency = 1; tbl.StatLabel_2.Position = UDim2.new(0.5, 0, 0, 0); tbl.StatLabel_2.SliceScale = 0; tbl.StatLabel_2.Parent = tbl.Padding_2; 
    tbl.Bar_2.ZIndex = 63; tbl.Bar_2.BorderSizePixel = 0; tbl.Bar_2.SliceCenter = Rect.new(5, 5, 5, 5); tbl.Bar_2.AutoLocalize = false; tbl.Bar_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Bar_2.Size = UDim2.new(1, 0, 1, 0); tbl.Bar_2.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Bar_2.Name = "Bar"; tbl.Bar_2.SliceScale = 0; tbl.Bar_2.Parent = tbl.Padding_2; 
    tbl.UIGradient_4.Name = "UIGradient"; tbl.UIGradient_4.Color = ColorSequence.new{ ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 128, 123)), ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 222, 151)) }; tbl.UIGradient_4.Rotation = 90; tbl.UIGradient_4.Parent = tbl.Bar_2; 
    tbl.Arrows_2.AnchorPoint = Vector2.new(1, 0); tbl.Arrows_2.ZIndex = 62; tbl.Arrows_2.BorderSizePixel = 0; tbl.Arrows_2.Size = UDim2.new(0, 30, 1, 0); tbl.Arrows_2.AutoLocalize = false; tbl.Arrows_2.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Arrows_2.BackgroundTransparency = 1; tbl.Arrows_2.Name = "Arrows"; tbl.Arrows_2.Position = UDim2.new(1, 0, 0, 0); tbl.Arrows_2.BackgroundColor3 = Color3.fromRGB(0, 0, 0); tbl.Arrows_2.Parent = tbl.Padding_2; 
    tbl.Up_2.ZIndex = 61; tbl.Up_2.Size = UDim2.new(1, 0, 1, 0); tbl.Up_2.AutoLocalize = false; tbl.Up_2.BackgroundTransparency = 1; tbl.Up_2.Visible = false; tbl.Up_2.Name = "Up"; tbl.Up_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Up_2.Parent = tbl.Arrows_2; 
    tbl._1_4.ZIndex = 70; tbl._1_4.BorderSizePixel = 0; tbl._1_4.AutoLocalize = false; tbl._1_4.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._1_4.AnchorPoint = Vector2.new(1, 0); tbl._1_4.Image = "http://www.roblox.com/asset/?id=4841959138"; tbl._1_4.Size = UDim2.new(0, 11, 0, 14); tbl._1_4.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._1_4.Name = "1"; tbl._1_4.BackgroundTransparency = 1; tbl._1_4.Position = UDim2.new(1, 0, 0, 0); tbl._1_4.Visible = false; tbl._1_4.Parent = tbl.Up_2; 
    tbl._2_4.ZIndex = 70; tbl._2_4.BorderSizePixel = 0; tbl._2_4.AutoLocalize = false; tbl._2_4.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._2_4.AnchorPoint = Vector2.new(1, 0); tbl._2_4.Image = "http://www.roblox.com/asset/?id=4841959138"; tbl._2_4.Size = UDim2.new(0, 11, 0, 14); tbl._2_4.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._2_4.Name = "2"; tbl._2_4.BackgroundTransparency = 1; tbl._2_4.Position = UDim2.new(1, -9, 0, 0); tbl._2_4.Visible = false; tbl._2_4.Parent = tbl.Up_2; 
    tbl._3_4.ZIndex = 70; tbl._3_4.BorderSizePixel = 0; tbl._3_4.AutoLocalize = false; tbl._3_4.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._3_4.AnchorPoint = Vector2.new(1, 0); tbl._3_4.Image = "http://www.roblox.com/asset/?id=4841959138"; tbl._3_4.Size = UDim2.new(0, 11, 0, 14); tbl._3_4.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._3_4.Name = "3"; tbl._3_4.BackgroundTransparency = 1; tbl._3_4.Position = UDim2.new(1, -18, 0, 0); tbl._3_4.Visible = false; tbl._3_4.Parent = tbl.Up_2; 
    tbl.Down_2.ZIndex = 61; tbl.Down_2.Size = UDim2.new(1, 0, 1, 0); tbl.Down_2.AutoLocalize = false; tbl.Down_2.BackgroundTransparency = 1; tbl.Down_2.Visible = false; tbl.Down_2.Name = "Down"; tbl.Down_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Down_2.Parent = tbl.Arrows_2; 
    tbl._1_5.ZIndex = 70; tbl._1_5.BorderSizePixel = 0; tbl._1_5.AutoLocalize = false; tbl._1_5.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._1_5.AnchorPoint = Vector2.new(1, 0); tbl._1_5.Image = "http://www.roblox.com/asset/?id=4841959303"; tbl._1_5.Size = UDim2.new(0, 11, 0, 14); tbl._1_5.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._1_5.Name = "1"; tbl._1_5.BackgroundTransparency = 1; tbl._1_5.Position = UDim2.new(1, 0, 0, 0); tbl._1_5.Visible = false; tbl._1_5.Parent = tbl.Down_2; 
    tbl._2_5.ZIndex = 70; tbl._2_5.BorderSizePixel = 0; tbl._2_5.AutoLocalize = false; tbl._2_5.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._2_5.AnchorPoint = Vector2.new(1, 0); tbl._2_5.Image = "http://www.roblox.com/asset/?id=4841959303"; tbl._2_5.Size = UDim2.new(0, 11, 0, 14); tbl._2_5.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._2_5.Name = "2"; tbl._2_5.BackgroundTransparency = 1; tbl._2_5.Position = UDim2.new(1, -9, 0, 0); tbl._2_5.Visible = false; tbl._2_5.Parent = tbl.Down_2; 
    tbl._3_5.ZIndex = 70; tbl._3_5.BorderSizePixel = 0; tbl._3_5.AutoLocalize = false; tbl._3_5.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl._3_5.AnchorPoint = Vector2.new(1, 0); tbl._3_5.Image = "http://www.roblox.com/asset/?id=4841959303"; tbl._3_5.Size = UDim2.new(0, 11, 0, 14); tbl._3_5.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl._3_5.Name = "3"; tbl._3_5.BackgroundTransparency = 1; tbl._3_5.Position = UDim2.new(1, -18, 0, 0); tbl._3_5.Visible = false; tbl._3_5.Parent = tbl.Down_2; 
    tbl.Booster_2.ZIndex = 64; tbl.Booster_2.BorderSizePixel = 0; tbl.Booster_2.SliceCenter = Rect.new(5, 5, 5, 5); tbl.Booster_2.AutoLocalize = false; tbl.Booster_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Booster_2.Size = UDim2.new(0, 0, 1, 0); tbl.Booster_2.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Booster_2.Name = "Booster"; tbl.Booster_2.SliceScale = 0; tbl.Booster_2.Parent = tbl.Padding_2; 
    tbl.Shadow_2.ZIndex = 64; tbl.Shadow_2.BorderSizePixel = 0; tbl.Shadow_2.SliceCenter = Rect.new(5, 5, 5, 5); tbl.Shadow_2.AutoLocalize = false; tbl.Shadow_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Shadow_2.ImageTransparency = 1; tbl.Shadow_2.Image = "http://www.roblox.com/asset/?id=4841891466"; tbl.Shadow_2.Size = UDim2.new(0, 14, 1, 0); tbl.Shadow_2.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Shadow_2.Name = "Shadow"; tbl.Shadow_2.BackgroundTransparency = 1; tbl.Shadow_2.Position = UDim2.new(1, 0, 0, 0); tbl.Shadow_2.SliceScale = 0; tbl.Shadow_2.Parent = tbl.Booster_2; 
    tbl.UIGradient_5.Name = "UIGradient"; tbl.UIGradient_5.Color = ColorSequence.new{ ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 123, 107)), ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 237, 86)) }; tbl.UIGradient_5.Rotation = 90; tbl.UIGradient_5.Parent = tbl.Booster_2; 
    tbl.UIScale.Name = "UIScale"; tbl.UIScale.Parent = tbl.Spectate; 
    tbl.Decoration.ZIndex = 0; tbl.Decoration.Size = UDim2.new(1, 0, 1, 0); tbl.Decoration.AutoLocalize = false; tbl.Decoration.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Decoration.BackgroundTransparency = 1; tbl.Decoration.Name = "Decoration"; tbl.Decoration.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Decoration.Parent = tbl.Spectate; 
    tbl.ShadowFrame.ZIndex = 0; tbl.ShadowFrame.BorderSizePixel = 0; tbl.ShadowFrame.Size = UDim2.new(0, 489, 0, 80); tbl.ShadowFrame.AutoLocalize = false; tbl.ShadowFrame.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.ShadowFrame.BackgroundTransparency = 1; tbl.ShadowFrame.Name = "ShadowFrame"; tbl.ShadowFrame.BackgroundColor3 = Color3.fromRGB(0, 0, 0); tbl.ShadowFrame.Parent = tbl.Decoration; 
    tbl.Shadow_3.ImageColor3 = Color3.fromRGB(0, 0, 0); tbl.Shadow_3.ZIndex = 60; tbl.Shadow_3.BorderSizePixel = 0; tbl.Shadow_3.SliceCenter = Rect.new(8, 8, 8, 8); tbl.Shadow_3.ScaleType = Enum.ScaleType.Slice; tbl.Shadow_3.AutoLocalize = false; tbl.Shadow_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Shadow_3.ImageTransparency = 0.75; tbl.Shadow_3.AnchorPoint = Vector2.new(0.5, 0.5); tbl.Shadow_3.Image = "http://www.roblox.com/asset/?id=4842144261"; tbl.Shadow_3.Size = UDim2.new(0, 511, 0, 102); tbl.Shadow_3.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Shadow_3.Name = "Shadow"; tbl.Shadow_3.BackgroundTransparency = 1; tbl.Shadow_3.Position = UDim2.new(0.5, 0, 0.5, 0); tbl.Shadow_3.Parent = tbl.ShadowFrame; 
    tbl.Wrap.ZIndex = 63; tbl.Wrap.BorderSizePixel = 0; tbl.Wrap.SliceCenter = Rect.new(8, 8, 8, 8); tbl.Wrap.ScaleType = Enum.ScaleType.Slice; tbl.Wrap.AutoLocalize = false; tbl.Wrap.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Wrap.Image = "http://www.roblox.com/asset/?id=4838695044"; tbl.Wrap.Size = UDim2.new(1, 0, 1, 0); tbl.Wrap.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Wrap.Name = "Wrap"; tbl.Wrap.BackgroundTransparency = 1; tbl.Wrap.Parent = tbl.Decoration; 
    tbl.TextBox.Active = true; tbl.TextBox.ZIndex = 2; tbl.TextBox.TextEditable = false; tbl.TextBox.AutoLocalize = false; tbl.TextBox.Selectable = true; tbl.TextBox.BackgroundColor3 = Color3.fromRGB(0, 0, 0); tbl.TextBox.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.SemiBold, Enum.FontStyle.Normal); tbl.TextBox.Position = UDim2.new(0, 0, 0, -2); tbl.TextBox.BackgroundTransparency = 1; tbl.TextBox.AnchorPoint = Vector2.new(0, 1); tbl.TextBox.TextSize = 22; tbl.TextBox.Size = UDim2.new(1, -124, 0, 32); tbl.TextBox.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.TextBox.BorderColor3 = Color3.fromRGB(0, 0, 0); tbl.TextBox.Text = "OnlyTwentyCharacters - 1234567890"; tbl.TextBox.Name = "TextBox"; tbl.TextBox.ClearTextOnFocus = false; tbl.TextBox.Parent = tbl.Spectate; 
    tbl.UICorner.Name = "UICorner"; tbl.UICorner.Parent = tbl.TextBox; 
    tbl.TextBox_1.TextStrokeTransparency = 0.8; tbl.TextBox_1.TextEditable = false; tbl.TextBox_1.AutoLocalize = false; tbl.TextBox_1.BackgroundColor3 = Color3.fromRGB(0, 0, 0); tbl.TextBox_1.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.SemiBold, Enum.FontStyle.Normal); tbl.TextBox_1.BackgroundTransparency = 1; tbl.TextBox_1.TextSize = 22; tbl.TextBox_1.ShowNativeInput = false; tbl.TextBox_1.Size = UDim2.new(1, 0, 1, 0); tbl.TextBox_1.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.TextBox_1.BorderColor3 = Color3.fromRGB(0, 0, 0); tbl.TextBox_1.Text = "OnlyTwentyCharacters - 1234567890"; tbl.TextBox_1.Name = "TextBox"; tbl.TextBox_1.ClearTextOnFocus = false; tbl.TextBox_1.Parent = tbl.TextBox; 
    tbl.UICorner_1.Name = "UICorner"; tbl.UICorner_1.Parent = tbl.TextBox_1; 
    tbl.Players.AnchorPoint = Vector2.new(1, 0); tbl.Players.BorderSizePixel = 0; tbl.Players.Size = UDim2.new(0, 60, 0, -32); tbl.Players.AutoLocalize = false; tbl.Players.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Players.BackgroundTransparency = 1; tbl.Players.Name = "Players"; tbl.Players.Position = UDim2.new(1, 0, 0, -2); tbl.Players.BackgroundColor3 = Color3.fromRGB(0, 0, 0); tbl.Players.Parent = tbl.Spectate; 
    tbl.Label.LayoutOrder = 1; tbl.Label.TextStrokeTransparency = 0.7; tbl.Label.BorderSizePixel = 0; tbl.Label.AutoLocalize = false; tbl.Label.BackgroundColor3 = Color3.fromRGB(0, 0, 0); tbl.Label.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal); tbl.Label.TextSize = 14; tbl.Label.Size = UDim2.new(1, 0, 0.5, 2); tbl.Label.Name = "Label"; tbl.Label.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Label.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Label.Text = "Players"; tbl.Label.BackgroundTransparency = 1; tbl.Label.Parent = tbl.Players; 
    tbl.UICorner_2.Name = "UICorner"; tbl.UICorner_2.Parent = tbl.Label; 
    tbl.Back.BorderSizePixel = 0; tbl.Back.AutoLocalize = false; tbl.Back.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Back.FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal); tbl.Back.TextColor3 = Color3.fromRGB(0, 0, 0); tbl.Back.AnchorPoint = Vector2.new(0, 1); tbl.Back.Position = UDim2.new(0, 0, 1, 0); tbl.Back.TextSize = 14; tbl.Back.Size = UDim2.new(0.5, -1, 0.5, -4); tbl.Back.Name = "Back"; tbl.Back.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Back.Text = "<"; tbl.Back.LayoutOrder = 2; tbl.Back.Active = true; tbl.Back.Selectable = true; tbl.Back.Parent = tbl.Players; 
    tbl.UICorner_3.Name = "UICorner"; tbl.UICorner_3.Parent = tbl.Back; 
    tbl.Next.BorderSizePixel = 0; tbl.Next.AutoLocalize = false; tbl.Next.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Next.FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal); tbl.Next.TextColor3 = Color3.fromRGB(0, 0, 0); tbl.Next.AnchorPoint = Vector2.new(1, 1); tbl.Next.Position = UDim2.new(1, 0, 1, 0); tbl.Next.TextSize = 14; tbl.Next.Size = UDim2.new(0.5, -1, 0.5, -4); tbl.Next.Name = "Next"; tbl.Next.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Next.Text = ">"; tbl.Next.LayoutOrder = 3; tbl.Next.Active = true; tbl.Next.Selectable = true; tbl.Next.Parent = tbl.Players; 
    tbl.UICorner_4.Name = "UICorner"; tbl.UICorner_4.Parent = tbl.Next; 
    tbl.StatLabels.Size = UDim2.new(1, 0, 1, 0); tbl.StatLabels.AutoLocalize = false; tbl.StatLabels.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.StatLabels.BackgroundTransparency = 1; tbl.StatLabels.Name = "StatLabels"; tbl.StatLabels.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.StatLabels.Parent = tbl.Spectate; 
    tbl.UIGridLayout.FillDirection = Enum.FillDirection.Vertical; tbl.UIGridLayout.CellPadding = UDim2.new(0, 20, 0, 0); tbl.UIGridLayout.SortOrder = Enum.SortOrder.LayoutOrder; tbl.UIGridLayout.Name = "UIGridLayout"; tbl.UIGridLayout.CellSize = UDim2.new(0.5, 0, 0.25, 0); tbl.UIGridLayout.Parent = tbl.StatLabels; 
    tbl.UIPadding.PaddingTop = UDim.new(0, 2); tbl.UIPadding.Name = "UIPadding"; tbl.UIPadding.PaddingBottom = UDim.new(0, 2); tbl.UIPadding.PaddingRight = UDim.new(0, 4); tbl.UIPadding.PaddingLeft = UDim.new(0, 70); tbl.UIPadding.Parent = tbl.StatLabels; 
    tbl.Menu.LayoutOrder = 1; tbl.Menu.Size = UDim2.new(0, 100, 0, 100); tbl.Menu.AutoLocalize = false; tbl.Menu.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Menu.BackgroundTransparency = 1; tbl.Menu.Name = "Menu"; tbl.Menu.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Menu.Parent = tbl.StatLabels; 
    tbl.Title.TextStrokeTransparency = 0.7; tbl.Title.ZIndex = 65; tbl.Title.AutoLocalize = false; tbl.Title.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Title.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal); tbl.Title.TextSize = 16; tbl.Title.Size = UDim2.new(0.2, 0, 1, 0); tbl.Title.Name = "Title"; tbl.Title.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Title.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Title.Text = "In Menu:"; tbl.Title.BackgroundTransparency = 1; tbl.Title.TextXAlignment = Enum.TextXAlignment.Right; tbl.Title.Parent = tbl.Menu; 
    tbl.Info.TextStrokeTransparency = 0.7; tbl.Info.ZIndex = 65; tbl.Info.AutoLocalize = false; tbl.Info.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Info.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal); tbl.Info.AnchorPoint = Vector2.new(1, 0); tbl.Info.TextSize = 16; tbl.Info.Position = UDim2.new(1, 0, 0, 0); tbl.Info.Size = UDim2.new(0.8, -4, 1, 0); tbl.Info.Name = "Info"; tbl.Info.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Info.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Info.Text = "Some Value.1234"; tbl.Info.BackgroundTransparency = 1; tbl.Info.TextXAlignment = Enum.TextXAlignment.Left; tbl.Info.Parent = tbl.Menu; 
    tbl.Equipped.LayoutOrder = 2; tbl.Equipped.Size = UDim2.new(0, 100, 0, 100); tbl.Equipped.AutoLocalize = false; tbl.Equipped.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Equipped.BackgroundTransparency = 1; tbl.Equipped.Name = "Equipped"; tbl.Equipped.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Equipped.Parent = tbl.StatLabels; 
    tbl.Title_1.TextStrokeTransparency = 0.7; tbl.Title_1.ZIndex = 65; tbl.Title_1.AutoLocalize = false; tbl.Title_1.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Title_1.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal); tbl.Title_1.TextSize = 16; tbl.Title_1.Size = UDim2.new(0.2, 0, 1, 0); tbl.Title_1.Name = "Title"; tbl.Title_1.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Title_1.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Title_1.Text = "Equipped:"; tbl.Title_1.BackgroundTransparency = 1; tbl.Title_1.TextXAlignment = Enum.TextXAlignment.Right; tbl.Title_1.Parent = tbl.Equipped; 
    tbl.Info_1.TextStrokeTransparency = 0.7; tbl.Info_1.ZIndex = 65; tbl.Info_1.AutoLocalize = false; tbl.Info_1.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Info_1.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal); tbl.Info_1.AnchorPoint = Vector2.new(1, 0); tbl.Info_1.TextSize = 16; tbl.Info_1.Position = UDim2.new(1, 0, 0, 0); tbl.Info_1.Size = UDim2.new(0.8, -4, 1, 0); tbl.Info_1.Name = "Info"; tbl.Info_1.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Info_1.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Info_1.Text = "Some Value.1234"; tbl.Info_1.BackgroundTransparency = 1; tbl.Info_1.TextXAlignment = Enum.TextXAlignment.Left; tbl.Info_1.Parent = tbl.Equipped; 
    tbl.Ping.LayoutOrder = 3; tbl.Ping.Size = UDim2.new(0, 100, 0, 100); tbl.Ping.AutoLocalize = false; tbl.Ping.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Ping.BackgroundTransparency = 1; tbl.Ping.Name = "Ping"; tbl.Ping.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Ping.Parent = tbl.StatLabels; 
    tbl.Title_2.TextStrokeTransparency = 0.7; tbl.Title_2.ZIndex = 65; tbl.Title_2.AutoLocalize = false; tbl.Title_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Title_2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal); tbl.Title_2.TextSize = 16; tbl.Title_2.Size = UDim2.new(0.2, 0, 1, 0); tbl.Title_2.Name = "Title"; tbl.Title_2.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Title_2.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Title_2.Text = "Ping:"; tbl.Title_2.BackgroundTransparency = 1; tbl.Title_2.TextXAlignment = Enum.TextXAlignment.Right; tbl.Title_2.Parent = tbl.Ping; 
    tbl.Info_2.TextStrokeTransparency = 0.7; tbl.Info_2.ZIndex = 65; tbl.Info_2.AutoLocalize = false; tbl.Info_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Info_2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal); tbl.Info_2.AnchorPoint = Vector2.new(1, 0); tbl.Info_2.TextSize = 16; tbl.Info_2.Position = UDim2.new(1, 0, 0, 0); tbl.Info_2.Size = UDim2.new(0.8, -4, 1, 0); tbl.Info_2.Name = "Info"; tbl.Info_2.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Info_2.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Info_2.Text = "Some Value.1234"; tbl.Info_2.BackgroundTransparency = 1; tbl.Info_2.TextXAlignment = Enum.TextXAlignment.Left; tbl.Info_2.Parent = tbl.Ping; 
    tbl.MoveState.LayoutOrder = 5; tbl.MoveState.Size = UDim2.new(0, 100, 0, 100); tbl.MoveState.AutoLocalize = false; tbl.MoveState.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.MoveState.BackgroundTransparency = 1; tbl.MoveState.Name = "MoveState"; tbl.MoveState.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.MoveState.Parent = tbl.StatLabels; 
    tbl.Title_3.TextStrokeTransparency = 0.7; tbl.Title_3.ZIndex = 65; tbl.Title_3.AutoLocalize = false; tbl.Title_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Title_3.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal); tbl.Title_3.TextSize = 16; tbl.Title_3.Size = UDim2.new(0.2, 0, 1, 0); tbl.Title_3.Name = "Title"; tbl.Title_3.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Title_3.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Title_3.Text = "MoveState:"; tbl.Title_3.BackgroundTransparency = 1; tbl.Title_3.TextXAlignment = Enum.TextXAlignment.Right; tbl.Title_3.Parent = tbl.MoveState; 
    tbl.Info_3.TextStrokeTransparency = 0.7; tbl.Info_3.ZIndex = 65; tbl.Info_3.AutoLocalize = false; tbl.Info_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Info_3.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal); tbl.Info_3.AnchorPoint = Vector2.new(1, 0); tbl.Info_3.TextSize = 16; tbl.Info_3.Position = UDim2.new(1, 0, 0, 0); tbl.Info_3.Size = UDim2.new(0.8, -4, 1, 0); tbl.Info_3.Name = "Info"; tbl.Info_3.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Info_3.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Info_3.Text = "Some Value.1234"; tbl.Info_3.BackgroundTransparency = 1; tbl.Info_3.TextXAlignment = Enum.TextXAlignment.Left; tbl.Info_3.Parent = tbl.MoveState; 
    tbl.FirstPerson.LayoutOrder = 6; tbl.FirstPerson.Size = UDim2.new(0, 100, 0, 100); tbl.FirstPerson.AutoLocalize = false; tbl.FirstPerson.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.FirstPerson.BackgroundTransparency = 1; tbl.FirstPerson.Name = "FirstPerson"; tbl.FirstPerson.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.FirstPerson.Parent = tbl.StatLabels; 
    tbl.Title_4.TextStrokeTransparency = 0.7; tbl.Title_4.ZIndex = 65; tbl.Title_4.AutoLocalize = false; tbl.Title_4.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Title_4.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal); tbl.Title_4.TextSize = 16; tbl.Title_4.Size = UDim2.new(0.2, 0, 1, 0); tbl.Title_4.Name = "Title"; tbl.Title_4.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Title_4.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Title_4.Text = "FirstPerson:"; tbl.Title_4.BackgroundTransparency = 1; tbl.Title_4.TextXAlignment = Enum.TextXAlignment.Right; tbl.Title_4.Parent = tbl.FirstPerson; 
    tbl.Info_4.TextStrokeTransparency = 0.7; tbl.Info_4.ZIndex = 65; tbl.Info_4.AutoLocalize = false; tbl.Info_4.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Info_4.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal); tbl.Info_4.AnchorPoint = Vector2.new(1, 0); tbl.Info_4.TextSize = 16; tbl.Info_4.Position = UDim2.new(1, 0, 0, 0); tbl.Info_4.Size = UDim2.new(0.8, -4, 1, 0); tbl.Info_4.Name = "Info"; tbl.Info_4.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Info_4.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Info_4.Text = "Some Value.1234"; tbl.Info_4.BackgroundTransparency = 1; tbl.Info_4.TextXAlignment = Enum.TextXAlignment.Left; tbl.Info_4.Parent = tbl.FirstPerson; 
    tbl.MoveSpeed.LayoutOrder = 8; tbl.MoveSpeed.Size = UDim2.new(0, 100, 0, 100); tbl.MoveSpeed.AutoLocalize = false; tbl.MoveSpeed.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.MoveSpeed.BackgroundTransparency = 1; tbl.MoveSpeed.Name = "MoveSpeed"; tbl.MoveSpeed.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.MoveSpeed.Parent = tbl.StatLabels; 
    tbl.Title_5.TextStrokeTransparency = 0.7; tbl.Title_5.ZIndex = 65; tbl.Title_5.AutoLocalize = false; tbl.Title_5.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Title_5.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal); tbl.Title_5.TextSize = 16; tbl.Title_5.Size = UDim2.new(0.2, 0, 1, 0); tbl.Title_5.Name = "Title"; tbl.Title_5.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Title_5.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Title_5.Text = "MoveSpeed:"; tbl.Title_5.BackgroundTransparency = 1; tbl.Title_5.TextXAlignment = Enum.TextXAlignment.Right; tbl.Title_5.Parent = tbl.MoveSpeed; 
    tbl.Info_5.TextStrokeTransparency = 0.7; tbl.Info_5.ZIndex = 65; tbl.Info_5.AutoLocalize = false; tbl.Info_5.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Info_5.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal); tbl.Info_5.AnchorPoint = Vector2.new(1, 0); tbl.Info_5.TextSize = 16; tbl.Info_5.Position = UDim2.new(1, 0, 0, 0); tbl.Info_5.Size = UDim2.new(0.8, -4, 1, 0); tbl.Info_5.Name = "Info"; tbl.Info_5.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Info_5.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Info_5.Text = "Some Value.1234"; tbl.Info_5.BackgroundTransparency = 1; tbl.Info_5.TextXAlignment = Enum.TextXAlignment.Left; tbl.Info_5.Parent = tbl.MoveSpeed; 
    tbl.Zooming.LayoutOrder = 7; tbl.Zooming.Size = UDim2.new(0, 100, 0, 100); tbl.Zooming.AutoLocalize = false; tbl.Zooming.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Zooming.BackgroundTransparency = 1; tbl.Zooming.Name = "Zooming"; tbl.Zooming.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Zooming.Parent = tbl.StatLabels; 
    tbl.Title_6.TextStrokeTransparency = 0.7; tbl.Title_6.ZIndex = 65; tbl.Title_6.AutoLocalize = false; tbl.Title_6.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Title_6.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal); tbl.Title_6.TextSize = 16; tbl.Title_6.Size = UDim2.new(0.2, 0, 1, 0); tbl.Title_6.Name = "Title"; tbl.Title_6.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Title_6.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Title_6.Text = "Zooming:"; tbl.Title_6.BackgroundTransparency = 1; tbl.Title_6.TextXAlignment = Enum.TextXAlignment.Right; tbl.Title_6.Parent = tbl.Zooming; 
    tbl.Info_6.TextStrokeTransparency = 0.7; tbl.Info_6.ZIndex = 65; tbl.Info_6.AutoLocalize = false; tbl.Info_6.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Info_6.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal); tbl.Info_6.AnchorPoint = Vector2.new(1, 0); tbl.Info_6.TextSize = 16; tbl.Info_6.Position = UDim2.new(1, 0, 0, 0); tbl.Info_6.Size = UDim2.new(0.8, -4, 1, 0); tbl.Info_6.Name = "Info"; tbl.Info_6.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Info_6.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Info_6.Text = "Some Value.1234"; tbl.Info_6.BackgroundTransparency = 1; tbl.Info_6.TextXAlignment = Enum.TextXAlignment.Left; tbl.Info_6.Parent = tbl.Zooming; 
    tbl.CombatTime.LayoutOrder = 4; tbl.CombatTime.Size = UDim2.new(0, 100, 0, 100); tbl.CombatTime.AutoLocalize = false; tbl.CombatTime.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.CombatTime.BackgroundTransparency = 1; tbl.CombatTime.Name = "CombatTime"; tbl.CombatTime.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.CombatTime.Parent = tbl.StatLabels; 
    tbl.Title_7.TextStrokeTransparency = 0.7; tbl.Title_7.ZIndex = 65; tbl.Title_7.AutoLocalize = false; tbl.Title_7.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Title_7.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal); tbl.Title_7.TextSize = 16; tbl.Title_7.Size = UDim2.new(0.2, 0, 1, 0); tbl.Title_7.Name = "Title"; tbl.Title_7.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Title_7.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Title_7.Text = "CombatTime:"; tbl.Title_7.BackgroundTransparency = 1; tbl.Title_7.TextXAlignment = Enum.TextXAlignment.Right; tbl.Title_7.Parent = tbl.CombatTime; 
    tbl.Info_7.TextStrokeTransparency = 0.7; tbl.Info_7.ZIndex = 65; tbl.Info_7.AutoLocalize = false; tbl.Info_7.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Info_7.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal); tbl.Info_7.AnchorPoint = Vector2.new(1, 0); tbl.Info_7.TextSize = 16; tbl.Info_7.Position = UDim2.new(1, 0, 0, 0); tbl.Info_7.Size = UDim2.new(0.8, -4, 1, 0); tbl.Info_7.Name = "Info"; tbl.Info_7.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Info_7.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Info_7.Text = "Unknown"; tbl.Info_7.BackgroundTransparency = 1; tbl.Info_7.TextXAlignment = Enum.TextXAlignment.Left; tbl.Info_7.Parent = tbl.CombatTime; 
    tbl.Groups.AnchorPoint = Vector2.new(1, 0); tbl.Groups.BorderSizePixel = 0; tbl.Groups.Size = UDim2.new(0, 60, 0, -32); tbl.Groups.AutoLocalize = false; tbl.Groups.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Groups.BackgroundTransparency = 1; tbl.Groups.Name = "Groups"; tbl.Groups.Position = UDim2.new(1, -62, 0, -2); tbl.Groups.BackgroundColor3 = Color3.fromRGB(0, 0, 0); tbl.Groups.Parent = tbl.Spectate; 
    tbl.Label_1.LayoutOrder = 1; tbl.Label_1.TextStrokeTransparency = 0.7; tbl.Label_1.BorderSizePixel = 0; tbl.Label_1.AutoLocalize = false; tbl.Label_1.BackgroundColor3 = Color3.fromRGB(0, 0, 0); tbl.Label_1.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal); tbl.Label_1.TextSize = 14; tbl.Label_1.Size = UDim2.new(1, 0, 0.5, 2); tbl.Label_1.Name = "Label"; tbl.Label_1.TextColor3 = Color3.fromRGB(255, 255, 255); tbl.Label_1.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Label_1.Text = "Group"; tbl.Label_1.BackgroundTransparency = 1; tbl.Label_1.Parent = tbl.Groups; 
    tbl.UICorner_5.Name = "UICorner"; tbl.UICorner_5.Parent = tbl.Label_1; 
    tbl.Back_1.BorderSizePixel = 0; tbl.Back_1.AutoLocalize = false; tbl.Back_1.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Back_1.FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal); tbl.Back_1.TextColor3 = Color3.fromRGB(0, 0, 0); tbl.Back_1.AnchorPoint = Vector2.new(0, 1); tbl.Back_1.Position = UDim2.new(0, 0, 1, 0); tbl.Back_1.TextSize = 14; tbl.Back_1.Size = UDim2.new(0.5, -1, 0.5, -4); tbl.Back_1.Name = "Back"; tbl.Back_1.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Back_1.Text = "<"; tbl.Back_1.LayoutOrder = 2; tbl.Back_1.Active = true; tbl.Back_1.Selectable = true; tbl.Back_1.Parent = tbl.Groups; 
    tbl.UICorner_6.Name = "UICorner"; tbl.UICorner_6.Parent = tbl.Back_1; 
    tbl.Next_1.BorderSizePixel = 0; tbl.Next_1.AutoLocalize = false; tbl.Next_1.BackgroundColor3 = Color3.fromRGB(255, 255, 255); tbl.Next_1.FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal); tbl.Next_1.TextColor3 = Color3.fromRGB(0, 0, 0); tbl.Next_1.AnchorPoint = Vector2.new(1, 1); tbl.Next_1.Position = UDim2.new(1, 0, 1, 0); tbl.Next_1.TextSize = 14; tbl.Next_1.Size = UDim2.new(0.5, -1, 0.5, -4); tbl.Next_1.Name = "Next"; tbl.Next_1.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Next_1.Text = ">"; tbl.Next_1.LayoutOrder = 3; tbl.Next_1.Active = true; tbl.Next_1.Selectable = true; tbl.Next_1.Parent = tbl.Groups; 
    tbl.UICorner_7.Name = "UICorner"; tbl.UICorner_7.Parent = tbl.Next_1; 
    tbl.Backdrop.ZIndex = -10; tbl.Backdrop.Size = UDim2.new(1, 0, 2, 0); tbl.Backdrop.AutoLocalize = false; tbl.Backdrop.BorderColor3 = Color3.fromRGB(28, 43, 54); tbl.Backdrop.BackgroundTransparency = 0.5; tbl.Backdrop.Name = "Backdrop"; tbl.Backdrop.Position = UDim2.new(0, 0, 0, -34); tbl.Backdrop.BackgroundColor3 = Color3.fromRGB(0, 0, 0); tbl.Backdrop.Parent = tbl.Spectate; 
    tbl.UICorner_8.Name = "UICorner"; tbl.UICorner_8.Parent = tbl.Backdrop; 

    local spectate = tbl.Spectate
    table.clear(tbl) -- // Since my name isn't LMH_Hutch

    local Part = Instance.new("Part")
    local ConeHandleAdornment = Instance.new("ConeHandleAdornment")
    local CylinderHandleAdornment = Instance.new("CylinderHandleAdornment")
    
    Part.Name = 'Part'; Part.TopSurface = Enum.SurfaceType.Smooth; Part.CanQuery = false; Part.Size = Vector3.new(1, 1, 1); Part.BottomSurface = Enum.SurfaceType.Smooth; Part.CanCollide = false; Part.Transparency = 1; Part.Anchored = true;
    ConeHandleAdornment.SizeRelativeOffset = Vector3.new(0, 0, -8); ConeHandleAdornment.Transparency = 0.5; ConeHandleAdornment.Color3 = Color3.fromRGB(0, 255, 0); ConeHandleAdornment.AlwaysOnTop = true; ConeHandleAdornment.Height = 1; ConeHandleAdornment.Name = "ConeHandleAdornment"; ConeHandleAdornment.Adornee = Part; ConeHandleAdornment.Parent = Part; 
    CylinderHandleAdornment.Radius = 0.2; CylinderHandleAdornment.AlwaysOnTop = true; CylinderHandleAdornment.SizeRelativeOffset = Vector3.new(0, 0, -4); CylinderHandleAdornment.Transparency = 0.5; CylinderHandleAdornment.Name = "CylinderHandleAdornment"; CylinderHandleAdornment.Color3 = Color3.fromRGB(0, 100, 0); CylinderHandleAdornment.Height = 4; CylinderHandleAdornment.Adornee = Part; CylinderHandleAdornment.Parent = Part; 

    return {spectate, Part}
end)()